import type { AppTheme } from './types';

// ──────────────────────────────────────────────────────────────────
// Ink Dark (Tokyo Night Moon — purple-gray dark theme)
// ──────────────────────────────────────────────────────────────────

export const INK_DARK: AppTheme = {
  id: 'ink-dark',
  isDark: true,
  colors: {
    'editor-background': '#222436',
    'sideBar-background': '#1e2030',
    'activityBar-background': '#1e2030',
    'sideBar-border': '#5a6590',
    'activityBar-border': '#5a6590',
    'widget-border': '#5a6590',
    'block-border': '#5a6590', // 代码块、表格等内容块边框，比 widget-border 略深更醒目
    'menu-border': '#5a6590',  // 浮窗菜单边框，与 block-border 一致
    'panel-border': '#5a6590',
    'foreground': '#c8d3f5',
    'descriptionForeground': '#7f88b0',
    'iconForeground': '#7f88b0',
    'focusBorder': '#82aaff',
    'button-background': '#82aaff',
    'button-foreground': '#1e2030',
    'button-hoverBackground': '#6090c0',
    'buttonSecondary-background': '#2f334d',
    'buttonSecondary-hoverBackground': '#3d415e',
    'buttonSecondary-foreground': '#c8d3f5',
    'input-background': '#1e2030',
    'input-border': '#5a6590',
    'input-foreground': '#c8d3f5',
    'input-placeholderForeground': '#7f88b0',
    'dropdown-background': '#1e2030',
    'dropdown-border': '#5a6590',
    'tab-activeBackground': '#222436',
    'tab-activeBorderTop': '#82aaff',
    'tab-activeForeground': '#c8d3f5',
    'tab-inactiveBackground': '#1e2030',
    'tab-inactiveForeground': '#7f88b0',
    'tab-border': '#5a6590',
    'menu-background': '#1e2030',
    'menu-hoverBackground': '#2f334d',
    'menu-separatorBackground': '#5a6590',
    'menu-selectionBackground': '#82aaff',
    'menu-selectionForeground': '#1e2030',
    'list-hoverBackground': '#2f334d',
    'list-activeSelectionBackground': '#2d3f76',
    'list-activeSelectionForeground': '#c8d3f5',
    'toolbar-hoverBackground': '#2f334d',
    'toolbar-activeBackground': '#3d415e',
    'titleBar-background': '#1e2030',
    'titleBar-border': '#5a6590',
    'titleBar-foreground': '#c8d3f5',
    'statusBar-background': '#1e2030',
    'statusBar-border': '#5a6590',
    'statusBar-foreground': '#c8d3f5',
    'sideBar-foreground': '#c8d3f5',
    'sideBarTitle-foreground': '#c8d3f5',
    'sideBarSectionHeader-background': '#1e2030',
    'sideBarSectionHeader-foreground': '#c8d3f5',
    'sideBarSectionHeader-border': '#5a6590',
    'activityBar-foreground': '#7f88b0',
    'editor-selectionBackground': '#2d3f76',
    'editor-inactiveSelectionBackground': '#2f334d',
    'panel-background': '#222436',
    'quickInput-background': '#1e2030',
    'editorWidget-background': '#1e2030',
    'scrollbarSlider-background': '#79797966',
    'scrollbarSlider-hoverBackground': '#79797999',
    'scrollbarSlider-activeBackground': '#797979AA',
    'badge-background': '#2f334d',
    'badge-foreground': '#c8d3f5',
    'progressBar-background': '#82aaff',
    'textLink-foreground': '#82aaff',
    'textLink-activeForeground': '#82aaff',
    'textBlockQuote-background': '#1e2030',
    'textBlockQuote-border': '#5a6590',
    'textCodeBlock-background': '#1e2030',
    'textPreformat-foreground': '#c8d3f5',
    'textPreformat-background': '#2f334d',
    'editorLineNumber-foreground': '#7f88b0',
    'editorLineNumber-activeForeground': '#c8d3f5',
    'editorIndentGuide-background1': '#2f334d',
    'editorIndentGuide-activeBackground1': '#82aaff',
    'editorGutter-addedBackground': '#c3e88d',
    'editorGutter-deletedBackground': '#ff757f',
    'editorGutter-modifiedBackground': '#82aaff',
    'errorForeground': '#ff757f',
    'editorWarning-foreground': '#ffc777',
    'editorInfo-foreground': '#86e1fc',
    'symbolIcon-eventForeground': '#ff966c',
    'symbolIcon-namespaceForeground': '#c099ff',
    'symbolIcon-fileForeground': '#82aaff',
    'symbolIcon-folderForeground': '#ffc777',
    'terminal-ansiGreen': '#c3e88d',
    'terminal-ansiBlue': '#82aaff',

    // ── Editor cursor ──
    'editorCursor-foreground': '#82aaff',

    'editGlow': '130 170 255', // Bright blue #82aaff
  },
  tokens: {
    'comment': '#7f88b0',
    'keyword': '#82aaff',
    'string': '#ffc777',
    'number': '#c3e88d',
    'function': '#c099ff',
    'type': '#86e1fc',
    'variable': '#c8d3f5',
    'constant': '#82aaff',
    'operator': '#7f88b0',
    'punctuation': '#586190',
    'invalid': '#ff757f',
    'regexp': '#ff966c',
    'escape': '#ffc777',
    'tag': '#ff757f',
    'attribute': '#ffc777',
    'deleted': '#ff757f',
    'inserted': '#c3e88d',
    'changed': '#82aaff',
    'markupHeading': '#ff757f',
    'markupBold': '#82aaff',
    'markupItalic': '#c099ff',
    'markupRaw': '#ffc777',
    'controlKeyword': '#c099ff',
  },
};
