import type { AppTheme } from './types';

// ──────────────────────────────────────────────────────────────────
// JStudio Dark (VSCode Dark Modern — current default)
// ──────────────────────────────────────────────────────────────────

export const JSTUDIO_DARK: AppTheme = {
  id: 'jstudio-dark',
  isDark: true,
  colors: {
    'editor-background': '#181818',
    'sideBar-background': '#1F1F1F',
    'activityBar-background': '#1F1F1F',
    'sideBar-border': '#5A5A5A',
    'activityBar-border': '#5A5A5A',
    'widget-border': '#5A5A5A',
    'block-border': '#5A5A5A', // 代码块、表格等内容块边框
    'menu-border': '#5A5A5A',  // 浮窗菜单边框
    'panel-border': '#5A5A5A',
    'foreground': '#CCCCCC',
    'descriptionForeground': '#9D9D9D',
    'iconForeground': '#CCCCCC',
    'focusBorder': '#07C160',
    'button-background': '#07C160',
    'button-foreground': '#FFFFFF',
    'button-hoverBackground': '#06AD56',
    'buttonSecondary-background': '#3A3D41',
    'buttonSecondary-hoverBackground': '#4A4D51',
    'buttonSecondary-foreground': '#FFFFFF',
    'input-background': '#313131',
    'input-border': '#5A5A5A',
    'input-foreground': '#CCCCCC',
    'input-placeholderForeground': '#6E6E6E',
    'dropdown-background': '#313131',
    'dropdown-border': '#5A5A5A',
    'tab-activeBackground': '#181818',
    'tab-activeBorderTop': '#07C160',
    'tab-activeForeground': '#FFFFFF',
    'tab-inactiveBackground': '#1F1F1F',
    'tab-inactiveForeground': '#9D9D9D',
    'tab-border': '#5A5A5A',
    'menu-background': '#1F1F1F',
    'menu-hoverBackground': '#2A2D2E',
    'menu-separatorBackground': '#3A3A3A',
    'menu-selectionBackground': '#07C160',
    'menu-selectionForeground': '#FFFFFF',
    'list-hoverBackground': '#F1F1F133',
    'list-activeSelectionBackground': '#F1F1F133',
    'list-activeSelectionForeground': '#FFFFFF',
    'toolbar-hoverBackground': '#404040',
    'toolbar-activeBackground': '#505050',
    'titleBar-background': '#1F1F1F',
    'titleBar-border': '#5A5A5A',
    'titleBar-foreground': '#CCCCCC',
    'statusBar-background': '#1F1F1F',
    'statusBar-border': '#5A5A5A',
    'statusBar-foreground': '#CCCCCC',
    'sideBar-foreground': '#CCCCCC',
    'sideBarTitle-foreground': '#CCCCCC',
    'sideBarSectionHeader-background': '#1F1F1F',
    'sideBarSectionHeader-foreground': '#CCCCCC',
    'sideBarSectionHeader-border': '#5A5A5A',
    'activityBar-foreground': '#D7D7D7',
    'editor-selectionBackground': '#ADD6FF26',
    'editor-inactiveSelectionBackground': '#3A3D41',
    'panel-background': '#181818',
    'quickInput-background': '#222222',
    'editorWidget-background': '#202020',
    'scrollbarSlider-background': '#79797966',
    'scrollbarSlider-hoverBackground': '#79797999',
    'scrollbarSlider-activeBackground': '#797979AA',
    'badge-background': '#616161',
    'badge-foreground': '#F8F8F8',
    'progressBar-background': '#07C160',
    'textLink-foreground': '#3DDC84',
    'textLink-activeForeground': '#3DDC84',
    'textBlockQuote-background': '#2B2B2B',
    'textBlockQuote-border': '#5A5A5A',
    'textCodeBlock-background': '#2B2B2B',
    'textPreformat-foreground': '#D0D0D0',
    'textPreformat-background': '#3C3C3C',
    'editorLineNumber-foreground': '#6E7681',
    'editorLineNumber-activeForeground': '#CCCCCC',
    'editorIndentGuide-background1': '#404040',
    'editorIndentGuide-activeBackground1': '#707070',
    'editorGutter-addedBackground': '#2EA043',
    'editorGutter-deletedBackground': '#F85149',
    'editorGutter-modifiedBackground': '#07C160',
    'errorForeground': '#F85149',
    'editorWarning-foreground': '#CCA700',
    'editorInfo-foreground': '#3794FF',
    'symbolIcon-eventForeground': '#EE9D28',
    'symbolIcon-namespaceForeground': '#B4009E',
    'symbolIcon-fileForeground': '#75BEFF',
    'symbolIcon-folderForeground': '#D4A259',
    'terminal-ansiGreen': '#4EC9B0',
    'terminal-ansiBlue': '#6796E6',

    // ── Editor cursor ──
    'editorCursor-foreground': '#07C160',

    'editGlow': '236 72 153', // Pink #EC4899

    // ── Table header background (neutral gray, matches textCodeBlock) ──
    'tableHeader-background': '#2B2B2B',
  },
  tokens: {
    'comment': '#6A9955',
    'keyword': '#569CD6',
    'string': '#CE9178',
    'number': '#B5CEA8',
    'function': '#DCDCAA',
    'type': '#4EC9B0',
    'variable': '#9CDCFE',
    'constant': '#4FC1FF',
    'operator': '#D4D4D4',
    'punctuation': '#808080',
    'invalid': '#F44747',
    'regexp': '#D16969',
    'escape': '#D7BA7D',
    'tag': '#569CD6',
    'attribute': '#9CDCFE',
    'deleted': '#CE9178',
    'inserted': '#B5CEA8',
    'changed': '#569CD6',
    'markupHeading': '#569CD6',
    'markupBold': '#569CD6',
    'markupItalic': '#C586C0',
    'markupRaw': '#CE9178',
    'controlKeyword': '#C586C0',
  },
};
