package store

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
	"time"
)

// ErrNotFound is returned when a requested row does not exist.
var ErrNotFound = errors.New("not found")

// ErrUsernameTaken is returned when registering an already used username.
var ErrUsernameTaken = errors.New("username already taken")

// uniqueConstraintMarker appears in SQLite UNIQUE constraint violation errors.
const uniqueConstraintMarker = "UNIQUE constraint failed"

// User is a registered account row.
type User struct {
	ID           string
	Username     string
	PasswordHash string
	CreatedAt    string
	UpdatedAt    string
}

// CreateUser inserts a new account. id is generated by the caller (UUIDv4).
func (s *Store) CreateUser(ctx context.Context, id, username, passwordHash string) (User, error) {
	now := time.Now().UTC().Format(time.RFC3339)
	u := User{ID: id, Username: username, PasswordHash: passwordHash, CreatedAt: now, UpdatedAt: now}
	_, err := s.db.ExecContext(ctx, `
		INSERT INTO users (id, username, password_hash, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?)`,
		u.ID, u.Username, u.PasswordHash, u.CreatedAt, u.UpdatedAt)
	if err != nil {
		if strings.Contains(err.Error(), uniqueConstraintMarker) {
			return User{}, ErrUsernameTaken
		}
		return User{}, fmt.Errorf("insert user: %w", err)
	}
	return u, nil
}

// GetUserByUsername looks up an account case-insensitively (the users.username
// column is declared COLLATE NOCASE).
func (s *Store) GetUserByUsername(ctx context.Context, username string) (User, error) {
	var u User
	err := s.db.QueryRowContext(ctx, `
		SELECT id, username, password_hash, created_at, updated_at
		FROM users WHERE username = ?`, username,
	).Scan(&u.ID, &u.Username, &u.PasswordHash, &u.CreatedAt, &u.UpdatedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return User{}, ErrNotFound
	}
	if err != nil {
		return User{}, fmt.Errorf("query user by username: %w", err)
	}
	return u, nil
}
