apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ required "minio.auth.rootUser 必填" .Values.auth.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ required "minio.auth.rootPassword 必填" .Values.auth.rootPassword | quote }}
